// src/store/menuStore.js
const hardness_options = [
  { key: "all", label: "全部", isActive: false },
  { key: "soft", label: "偏軟", isActive: false },
  { key: "soft_with_support", label: "軟有支撐", isActive: false },
  { key: "medium_hardness", label: "軟硬適中", isActive: false },
  { key: "hard_and_sticky", label: "硬有服貼", isActive: false },
  { key: "hard", label: "偏硬", isActive: false },
];

const user_options = [
  { key: "all", label: "全部", isActive: false },
  { key: "home_use", label: "家用型", isActive: false },
  { key: "rental", label: "出租型", isActive: false },
  { key: "customized_h_s_f", label: "客製", isActive: false }, // hardness_size_fabric
];

const structure_options = [
  { key: "all", label: "全部", isActive: false },
  { key: "high_strength_series", label: "串聯式設計", isActive: false },
  { key: "individual_spring", label: "獨立筒型彈簧", isActive: false },
];

// product_id: 商品 id, 根據這個 id 決定在 list 顯示的順序
// product_hash: 同一個商品的不同規格版本, user 之後可能會改成英文
export default {
  mattresses: {
    text: "床墊",
    aside_menu: [
      {
        key: "hardness",
        title: "軟硬度",
        icon: "/assets/images/index/headerIcon_hardness.png",
        banner: "/assets/images/product/list/hardness.png",
        items: [
          {
            text: "偏軟",
            key: "soft",
            tabs: hardness_options,
            isActive: false,
          },
          {
            text: "軟有支撐",
            key: "soft_with_support",
            tabs: hardness_options,
            isActive: false,
          },
          {
            text: "軟硬適中",
            key: "medium_hardness",
            tabs: hardness_options,
            isActive: false,
          },
          {
            text: "硬有服貼",
            key: "hard_and_sticky",
            tabs: hardness_options,
            isActive: false,
          },
          {
            text: "偏硬",
            key: "hard",
            tabs: hardness_options,
            isActive: false,
          },
        ],
      },
      {
        key: "users",
        title: "使用族群",
        icon: "/assets/images/index/headerIcon_users.png",
        banner: "/assets/images/product/list/users.png",
        items: [
          {
            text: "家用型",
            key: "home_use",
            tabs: [
              { key: "all", label: "全部", isActive: false },
              { key: "thick_cotton_lining", label: "厚實棉襯", isActive: false },
              { key: "1cm_latex", label: "1cm乳膠", isActive: false },
              { key: "2.54cm_latex", label: "2.54cm乳膠", isActive: false },
              { key: "5.08cm_latex", label: "5.08cm乳膠", isActive: false },
            ],
            isActive: false,
          },
          {
            text: "出租型",
            key: "rental",
            tabs: [
              { key: "all", label: "全部", isActive: false },
              { key: "office_suite", label: "上班套房", isActive: false },
              { key: "student_suite", label: "學生套房", isActive: false },
            ],
            isActive: false,
          },
          {
            text: "客製(軟硬/尺寸/表布)",
            key: "customized_h_s_f", // hardness_size_fabric
            tabs: [
              { key: "all", label: "全部", isActive: false },
              { key: "landlord_agent", label: "房東仲介", isActive: false },
              { key: "designer", label: "設計師", isActive: false },
            ],
            isActive: false,
          },
        ],
      },
      {
        key: "structure",
        title: "床墊結構",
        icon: "/assets/images/index/headerIcon_structure.png",
        banners: ['/assets/images/product/list/structure1.png', '/assets/images/product/list/structure2.png'],
        items: [
          {
            text: "高強度*串聯式設計",
            key: "high_strength_series",
            new: true,
            banners: [
              {
                img_pc: "/assets/images/index/banner_kari02_pc.jpg",
                img_mo: "/assets/images/index/banner_kari02_mo.jpg",
                name: "banner_kari02",
                title: "",
                desc: "",
                btn_text: "",
                btn_link: "",
              },
              {
                img_pc: "/assets/images/index/banner_kari03_pc.jpg",
                img_mo: "/assets/images/index/banner_kari03_mo.jpg",
                name: "banner_kari03",
                title: "",
                desc: "",
              },
            ],
            tabs: [
              { key: "all", label: "全部", isActive: false },
              { key: "high_carbon_steel", label: "高碳鋼", isActive: false },
              { key: "Q_spring", label: "Q彈簧", isActive: false },
              { key: "hotel_alloy", label: "飯店合金", isActive: false },
              { key: "special_alloy", label: "特殊合金", isActive: false },
            ],
            isActive: false,
          },
          {
            text: "獨立筒型彈簧",
            key: "individual_spring",
            tabs: [
              { key: "all", label: "全部", isActive: false },
              { key: "straight_through_type", label: "直排式", isActive: false },
              { key: "honeycomb_style", label: "蜂巢式", isActive: false },
              { key: "hard_independent_cylinder", label: "硬式獨立筒", isActive: false },
            ],
            isActive: false,
          },
        ],
      },
    ],
    products_obj: [
      {
        product_type: "hard_spring",
        product_id: 1,
        product_hash: 1,
        img: "/assets/images/product/bed/1/card.jpg",
        name: "淺波舒眠床墊",
        price: 6800,
        desc: "適合容易腰酸者，擁有高支撐力，波浪般服貼腰際，享受扎實睡感...",
        hardness_degree: 6,
        tag_en: ['hard_and_sticky', 'home_use', 'high_strength_series', '1cm_latex', 'high_carbon_steel'],
      },
      {
        product_type: "pocket_spring",
        product_id: 2,
        product_hash: 1,
        img: "/assets/images/product/bed/2/card.jpg",
        name: "綿雲舒壓床墊",
        price: 6800,
        desc: "適合容易腰酸者，擁有高支撐力，波浪般服貼腰際，享受扎實睡感...",
        hardness_degree: 3,
        tag_en: ['soft','home_use',	'individual_spring', '1cm_latex'],
      },
      {
        product_type: "elastic_spring",
        product_id: 3,
        product_hash: 1,
        img: "/assets/images/product/bed/3/card.jpg",
        name: "綿Q托付床墊",
        price: 9000,
        desc: "適合容易腰酸者，擁有高支撐力，波浪般服貼腰際，享受扎實睡感...",
        hardness_degree: 3,
        tag_en: ['medium_hardness', 'home_use', 'high_strength_series', '2.54cm_latex', 'Q_spring'],
      },
      {
        product_type: "titanium_spring",
        product_id: 4,
        product_hash: 1,
        img: "/assets/images/product/bed/4/card.jpg",
        name: "涼感魔力彈韌床墊",
        price: 13800,
        desc: "適合容易腰酸者，擁有高支撐力，波浪般服貼腰際，享受扎實睡感...",
        hardness_degree: 3,
        tag_en: ['soft_with_support', 'home_use', 'high_strength_series', '2.54cm_latex', 'hotel_alloy'],
      },
      {
        product_type: "alternating_spring",
        product_id: 5,
        product_hash: 1,
        img: "/assets/images/product/bed/5/card.jpg",
        name: "夢幻之星床墊",
        price: 14800,
        desc: "適合容易腰酸者，擁有高支撐力，波浪般服貼腰際，享受扎實睡感...",
        hardness_degree: 3,
        tag_en: ['soft', 'home_use', 'individual_spring', '5.08cm_latex', 'honeycomb_style'],
      },
      {
        product_type: "handmade_spring",
        product_id: 6,
        product_hash: 1,
        img: "/assets/images/product/bed/6/card.jpg",
        name: "輕雲繚繞薄床墊",
        price: 9800,
        desc: "適合容易腰酸者，擁有高支撐力，波浪般服貼腰際，享受扎實睡感...",
        hardness_degree: 4,
        tag_en: ['medium_hardness', 'customized', 'high_strength_series', '2.54cm_latex', 'high_carbon_steel'],
      },
    ],
  },

  bedframe: {
    text: "床架/床頭櫃",
    aside_menu: [
      {
        key: "bedside_table_cabinet",
        title: "床頭片/櫃",
        icon: "/assets/images/index/bed_cabinet.png",
        banner: "/assets/images/product/bed_set/banner_bed_cabinet.jpg",
        items: [
          {
            text: "木質床頭片",
            key: "wooden_headboard",
            isActive: false,
          },
          {
            text: "軟墊床頭片",
            key: "upholstered_headboard",
            isActive: false,
          },
          {
            text: "書架型床頭",
            key: "bookshelf_shaped_bedside",
            isActive: false,
          },
          {
            text: "收納床頭櫃",
            key: "storage_bedside_table",
            isActive: false,
          },
        ],
      },
      {
        key: "bedstead",
        title: "床架",
        icon: "/assets/images/index/bed_stead.png",
        banner: "/assets/images/product/bed_set/banner_bed_stead.jpg",
        items: [
          {
            text: "油壓式掀床架",
            key: "hydraulic_bed_lift",
            isActive: false,
          },
          {
            text: "雙拼式床架",
            key: "double_bed_frame",
            isActive: false,
          },
          {
            text: "日式木腳床架",
            key: "Japanese_style_wooden_leg_bed_frame",
            isActive: false,
          },
        ],
      },
      {
        key: "bed_set",
        title: "床組(含床頭)",
        icon: "/assets/images/index/bed_set.png",
        banner: "/assets/images/product/bed_set/banner_bed_set.jpg",
        items: [
          {
            text: "皮革實木鋼構床組",
            key: "leather_solid_wood_steel_structure_bed_set",
            banners: [
              {
                img_pc: "/assets/images/index/banner_kari02_pc.jpg",
                img_mo: "/assets/images/index/banner_kari02_mo.jpg",
                name: "banner_kari02",
                title: "",
                desc: "",
                btn_text: "",
                btn_link: "",
              },
              {
                img_pc: "/assets/images/index/banner_kari03_pc.jpg",
                img_mo: "/assets/images/index/banner_kari03_mo.jpg",
                name: "banner_kari03",
                title: "",
                desc: "",
              },
            ],
            tabs: [
              { key: "all", label: "全部", isActive: false },
              { key: "high_carbon_steel", label: "高碳鋼", isActive: false },
              { key: "Q_spring", label: "Q彈簧", isActive: false },
              { key: "hotel_alloy", label: "飯店合金", isActive: false },
              { key: "special_alloy", label: "特殊合金", isActive: false },
            ],
            isActive: false,
          },
          {
            text: "皮革收納鋼構床組",
            key: "leather_storage_steel_bed_set",
            tabs: [
              { key: "all", label: "全部", isActive: false },
              { key: "straight_through_type", label: "直排式", isActive: false },
              { key: "honeycomb_style", label: "蜂巢式", isActive: false },
              { key: "hard_independent_cylinder", label: "硬式獨立筒", isActive: false },
            ],
            isActive: false,
          },
        ],
      },
    ],
    products_obj: [
      {
        product_type: "lifted_storage_bed",
        product_id: 1,
        product_hash: 1,
        img: "/assets/images/product/bed_set/1/card.jpg",
        name: "原廠油壓式掀床-有框版",
        price: 6800,
        desc: "適合容易腰酸者，擁有高支撐力，波浪般服貼腰際，享受扎實睡感...",
        tag_en: ['hydraulic_bed_lift'],
      },
      {
        product_type: "cabinet_storage_bed",
        product_id: 2,
        product_hash: 1,
        img: "/assets/images/product/bed_set/2/card.jpg",
        name: "雙拼木心板床架-有抽屜",
        price: 4000,
        desc: "適合容易腰酸者，擁有高支撐力，波浪般服貼腰際，享受扎實睡感...",
        tag_en: ['double_bed_frame'],
      },
      {
        product_type: "japanese_style_bed",
        product_id: 3,
        product_hash: 1,
        img: "/assets/images/product/bed_set/3/card.jpg",
        name: "日式實木腳底床架",
        price: 5000,
        desc: "適合容易腰酸者，擁有高支撐力，波浪般服貼腰際，享受扎實睡感...",
        tag_en: ['Japanese_style_wooden_leg_bed_frame'],
      },
      {
        product_type: "leather_bed",
        product_id: 4,
        product_hash: 1,
        img: "/assets/images/product/bed_set/4/card.jpg",
        name: "質感皮面床架(A/B/C款)",
        price: 8500,
        desc: "適合容易腰酸者，擁有高支撐力，波浪般服貼腰際，享受扎實睡感...",
        tag_en: ['double_bed_frame'],
      },
      {
        product_type: "leather_headboard",
        product_id: 5,
        product_hash: 1,
        img: "/assets/images/product/bed_set/5/card.jpg",
        name: "質感皮面床頭片(A/B款)",
        price: 4500,
        desc: "適合容易腰酸者，擁有高支撐力，波浪般服貼腰際，享受扎實睡感...",
        tag_en: ['upholstered_headboard'],
      },
      {
        product_type: "wooden_headboard",
        product_id: 6,
        product_hash: 1,
        img: "/assets/images/product/bed_set/6/card.jpg",
        name: "福氣系列床頭片-(木心板)",
        price: 1299,
        desc: "適合容易腰酸者，擁有高支撐力，波浪般服貼腰際，享受扎實睡感...",
        tag_en: ['wooden_headboard'],
      },
      {
        product_type: "wooden_headboard",
        product_id: 7,
        product_hash: 2,
        img: "/assets/images/product/bed_set/7/card.jpg",
        name: "星芒系列床頭片-(木心板)",
        price: 2599,
        desc: "適合容易腰酸者，擁有高支撐力，波浪般服貼腰際，享受扎實睡感...",
        tag_en: ['upholstered_headboard'],
      },
      {
        product_type: "storage_headboard",
        product_id: 8,
        product_hash: 1,
        img: "/assets/images/product/bed_set/8/card.jpg",
        name: "輕巧書櫃床頭-(木心板)",
        price: 4999,
        desc: "適合容易腰酸者，擁有高支撐力，波浪般服貼腰際，享受扎實睡感...",
        tag_en: ['bookshelf_shaped_bedside'],
      },
      {
        product_type: "storage_headboard",
        product_id: 9,
        product_hash: 2,
        img: "/assets/images/product/bed_set/9/card.jpg",
        name: "軟墊書櫃床頭-(木心板)",
        price: 5999,
        desc: "適合容易腰酸者，擁有高支撐力，波浪般服貼腰際，享受扎實睡感...",
        tag_en: ['bookshelf_shaped_bedside'],
      },
      {
        product_type: "leather_storage_bed",
        product_id: 10,
        product_hash: 1,
        img: "/assets/images/product/bed_set/10/card.jpg",
        name: "義式皮革式床組(抽屜)",
        price: 5999,
        desc: "適合容易腰酸者，擁有高支撐力，波浪般服貼腰際，享受扎實睡感...",
        tag_en: ['leather_storage_steel_bed_set'],
      },
    ],
  }
}
